identifier: randomproblems
title: randomproblems
blueprint: service
properties:
  myStringProp: myValue
  myNumberProp: 5
  myUrlProp: https://example.com
  isthisreal: fantasea
relations:
  mySingleRelation: myTargetEntity
